---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: landing
  uid: 3a1c2174-50b8-4db8-bffb-2a604393eaa4
  resourceVersion: '14645995'
  creationTimestamp: '2022-10-17T20:19:29Z'
  labels:
    k8s-app: frontend
spec:
  ports:
    - name: tcp-3000
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    k8s-app: frontend