---
kind: Service
apiVersion: v1
metadata:
    name: frontend
    namespace: landing
    labels:
        k8s-app: frontend
spec:
    ports:
        - name: tcp-3000
          protocol: TCP
          port: 3000
          targetPort: 3000
    selector:
        k8s-app: frontend
