name: Prettier Code Format Check

on: [push, pull_request, workflow_dispatch]

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Prettier
      run: npm install --save-dev prettier

    - name: Install dependencies
      run: npm install

    - name: Check for formatting errors
      run: npx prettier --check .
