name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "{date}={$(date +'%Y-%m-%d')}" >> $GITHUB_OUTPUT
      
      - name: Show where we at
        run: ls

      - name: Get current branch hash
        id: branch
        run: echo "{branch}={$(git rev-parse --short "$GITHUB_REF")}" >> $GITHUB_OUTPUT 

      - name: Test with environment variables
        run: echo $REACT_APP_RELEASE_NAME
        env:
          REACT_APP_RELEASE_NAME: release-${{ steps.date.outputs.date }}-${{ steps.branch.outputs.branch }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.cloud.cbh.kth.se/landing/landing-frontend:latest

