name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set release env
        run: echo "REACT_APP_RELEASE_DATE=$( date '+%F_%H:%M' )" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.cloud.cbh.kth.se/landing/landing-frontend:latest
          context: .
          build-args: |
            "RELEASE_BRANCH=release"
            "RELEASE_DATE=${{ env.REACT_APP_RELEASE_DATE }}"
            "RELEASE_COMMIT=${{ github.sha }}"
