name: Build and deploy to beta.app.cloud.cbh.kth.se
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  kthcloud-ci-beta:
    runs-on: ubuntu-latest
    steps:
      - name: Set release env
        run: echo "RELEASE_DATE=$( date '+%F_%H:%M' )" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.BETA_DOCKER_USERNAME }}
          password: ${{ secrets.BETA_DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.BETA_DOCKER_TAG }}
          build-args: |
            "RELEASE_BRANCH=beta"
            "RELEASE_DATE=${{ env.RELEASE_DATE }}"
            "RELEASE_COMMIT=${{ github.sha }}"
