name: kthcloud-ci-beta
on:
  push:
    branches:
      - "beta"
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set release env
        run: echo "RELEASE_DATE=$( date '+%F_%H:%M' )" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.BETA_DOCKER_USERNAME }}
          password: ${{ secrets.BETA_DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.cloud.cbh.kth.se/deploy-3cf9c142-b974-4b8b-b979-e057da3b6ae3/landing-beta
          build-args: |
            "RELEASE_BRANCH=beta"
            "RELEASE_DATE=${{ env.RELEASE_DATE }}"
            "RELEASE_COMMIT=${{ github.sha }}"
